name: Mobile Python Testing

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      test:
        type: choice
        description: Test to launch
        options:
        - test_mobile_mfp
        - test_mobile_mfp_second_part
        
jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Pull project
      uses: actions/checkout@v3
      
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.6'
      
    - name: Setup appium
      run: |
          npm install -g appium@v1.22
          appium -v
          appium &>/dev/null &
          
    - name: Setup different needs
      run: python -m pip install -r requirements.txt
      
    - name: Run appium android tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: 29
          script: python -m pytest -s -v tests_python/mobileTest/MFP/${{ github.event.inputs.test || 'test_mobile_mfp' }}.py --email ${{ secrets.TEST_EMAIL }} --password ${{ secrets.TEST_PASSWORD }}
